### ISSUE TITLE
Merge OSAIC repo with OSAIC-site-policy repo

### ISSUE THREAD

**Issue by jmerlan** [OpenAIM/Community-Guidelines#1]

**Comment by vdubya** [comment]
After review, the Open Data Kit governance seemed more in line with our community guideline needs than the GitHub site policy documents. PR #6 reflects this.

**Comment by vdubya** [comment]
And if anybody is wondering, OSAIC was one of the many names we considered which stood for Open Source Asset Information Community. Ultimately OpenAIM we found to be more appropriate, not to mention easier to say :)
